name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Deploy to production
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        with:
          server: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          destination: ${{ secrets.DEPLOY_DESTINATION }}
