# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Octopus-Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3.5.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_a9c0e3d0e3054d05b7cc84710067cc47 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cbf6dd80008e488b89736d595c9ee803 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_a9c0e3d0e3054d05b7cc84710067cc47 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Octopus-Production'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e582cc9eafbc465f863f72114aced263 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_a9c0e3d0e3054d05b7cc84710067cc47 }}/appsvc/staticsite:${{ github.sha }}'